### PR TITLE
Update gradle version

### PR DESCRIPTION
**Pull request by JcMinarro**
The purpose of this PR is to upgrade the gradle version used to compile the project to version 4.2. That version is needed to use the new version of the `Android Build Gradle Plugin`, currently version 3.0.0-rc1

The new version is not supported yet because there is an issue compiling an Android project that uses kotlin (I am going to open an Issue with the information too ;) ), but I have unified the version of `Android Build Gradle Plugin` to version 2.3.3 to use the same version into all project.

On the other hand, to be able to use Gradle 4.2 I have had to upgrade the version of `Build Scan Plugin` to the last version because the version used until now wasn't supported with the new Gradle Version.

### CODE REVIEW

**Comment by AndrewReitz** [comment]
Thanks @JcMinarro, just kicked off another build looks like the last one hung.

**Comment by JcMinarro** [comment]
Eyy @AndrewReitz 
I am not sure why it fails on travis.
I have run the same gradle command on my machine and it works fine, spend a lot of time, but all tests are passed.
Maybe some groovy version?

**Comment by AndrewReitz** [comment]
It's hanging on my machine with the kotlin tests. The task jenkins is running is `fullTest` btw.

**Comment by JcMinarro** [comment]
I have tried with the gradle version that I have installed on my machine, it is the version 4.2

`gradle -q -s -Dscan -PbuildInfo.build.number=100 -PbuildInfo.buildUrl=https://travis-ci.org/asdf/builds/100 -PbuildInfo.buildAgent.name=jcminarro -PbuildInfo.principal=jcminarro --debug --info clean assemble check fullTest`

Maybe the wrapper is not right generated. I am going to try lanching it with the wrapper and I will post again tomorrow if it worked or not.

**Comment by JcMinarro** [comment]
Yes, it worked on my machine, here is the report of Build Scan:
https://scans.gradle.com/s/lb5x42c4ca2ki/

**Comment by autonomousapps** [comment]
Any news on this? I would LOVE if 1.3.0 of this plugin got released with support for Android Gradle Plugin 3.0.0 and Kotlin.

**Comment by AndrewReitz** [comment]
@autonomousapps in progress.

**Comment by JcMinarro** [comment]
@AndrewReitz Could we reduce the verbosity of the gradle command? It seems that is exceeding the max size allowed by travis and that is because the build is failing ever an ever
`The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).`

**Pull request merged**
