### PR TITLE
build.gradle updates

### PR DESCRIPTION
**Pull request by jaredsburrows**
- Switched from OpenJDK to OracleJDK
- Updated readme for update plugin version
- Updated bintray plugin
- Updated artifactory plugin
- Updated Groovy
- Updated Gradle

@melix, I see that the `gradle.properties` version is set to `0.3.7-SNAPSHOT` and the snapshot **has not been** released: http://oss.jfrog.org/oss-snapshot-local/org/codehaus/groovy/gradle-groovy-android-plugin/.

I am guessing this is because the build is failing: https://travis-ci.org/groovy/groovy-android-gradle-plugin.

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@melix Have you seen my updates?

**Comment by jaredsburrows** [comment]
@melix Have you seen my updates?

**Comment by melix** [comment]
Just checked the update. Not sure what benefits the PR now brings. I would tend to close it.

**Comment by jaredsburrows** [comment]
@melix I find that funny that you took part of my pull request and made changes to master anyways.

I mentioned here, https://github.com/groovy/groovy-android-gradle-plugin/issues/44, that I was having issues and later found out here that the `0.3.6` release was already out, https://github.com/groovy/groovy-android-gradle-plugin/issues/43. So it turns out that is repository needed the `README.md` to be updated so I made a PR, 7 days ago.

Even after you saw both of those issues and 4 days ago you "reviewed" my PR, you still "updated" the `README.md`.

**Pull request closed without merging**
